### ISSUE TITLE
Documentation: exponentialBackoff doesn't mention that it grows by 2

### ISSUE THREAD

**Issue by rrnewton** [Soostone/retry#26]
Likewise, another small doc tweak would be to mention that iteration numbers start at `0`, not `1`.  (I had to look at the source to figure that out.)

**Comment by ozataman** [comment]
Thanks - happy to incorporate any PRs :-)

**Comment by rrnewton** [comment]
So small it's only barely worth the fork noise ;-), but I went ahead and did this on PR #27.
