### ISSUE TITLE
Re-upload a release

### ISSUE THREAD

**Issue by k-bx** [Soostone/retry#38]
There seems to be a [weird issue](https://github.com/fpco/stackage/issues/1353) with latest retry package. I don't know the source of the problem yet, but it seems that re-uploading latest master code as a new version release could resolve the problem.

**Comment by MichaelXavier** [comment]
We had a bugfix to release anyways so I've released 0.7.2. Please let me know if this resolves the issue and if not, what I can do.

**Comment by k-bx** [comment]
Thank you. Closing for now.
