### ISSUE TITLE
Release or update Hackage metadata for compatibility with GHC 8.0.1.

### ISSUE THREAD

**Issue by borsboom** [Soostone/retry#43]
Already mentioned in #41, but thought I should make it a separate issue: Can we get a new Hackage release (or just an update to the existing package metadata) that loosens the bounds on ghc-prim, so that retry builds with GHC 8.0.1 and can be included in new Stackage nightly snapshots (which are now GHC 8.0.1-based)?

**Comment by gregwebs** [comment]
yes, that would be great. This is holding up amazonka.

**Comment by MichaelXavier** [comment]
@borsboom @gregwebs I'll be looking into this today. Thanks for bringing it to my attention.

**Comment by MichaelXavier** [comment]
Released at 0.7.3 http://hackage.haskell.org/package/retry-0.7.3

Let me know if anything else is needed!
