### ISSUE TITLE
Support for resumable retrying

### ISSUE THREAD

**Issue by jship** [Soostone/retry#74]
I have a use case (asynchronous job runner) where it would be useful to be able to specify the initial `RetryStatus` in a retrying/recovering operation.  Here is a demo commit adding just resumable `recovering` variants here: https://github.com/jship/retry/commit/75ae34e9aed97668911bce6bcd85cc2a7a7384b4

For more context on my use case, a job consists of some number of tasks, and the result of executing each task is persisted to the database. If the process dies and a task didn't complete, the job runner will pick up on that task again on process restart. The execution of each task is wrapped up in a `recovering` block.  The tasks in a job may potentially be long-running, so it would be useful if `Control.Retry` exposed a means for "resuming" a retrying operation.  In a simple case, if I set up a `RetryPolicy` on a long-running task via `limitRetries 1`, and the task threw an exception after some amount of time then began its retry run and then the process died, on restart of the process, the task would restart and so starts progressing through its `RetryPolicy` from scratch.

I'm curious if there is interest in resumable retrying as a whole, and if so, am happy to PR support for it.

**Comment by MichaelXavier** [comment]
I think this sounds like it could be useful. We've actually been doing something along similar lines. We have an SQS based job system and a local database table of jobs. We store a serialized version of `RetryStatus` in the database table and use [applyPolicy](https://hackage.haskell.org/package/retry-0.9.0.0/docs/Control-Retry.html#v:applyPolicy) to determine the retry parameters on failure or if we should just let the job fail permanently.

i would say as long as the change is additive only, there's a good motivating example in the docs and a test, I think this would be a great addition!

**Comment by jship** [comment]
This was added in #77, so gonna close this issue out 👍
